### ISSUE TITLE
`--stash` doesn't always purge stale warnings

### ISSUE THREAD

**Issue by natefaubion** [natefaubion/purescript-psa#10]
If you have a bunch of warnings for a file, fix them all, and then recompile it will still show the old warnings. This is because when we merge old warnings, it only purges old warnings for a file if there are warnings for it in the new set. Since there are no warnings at all, it thinks it should still show the old ones.

What we need to do is store a timestamp on each compilation, and then check file modification times for old warnings when merging. If a file has been modified after the last compilation, we should purge its stash.

**Comment by paulyoung** [comment]
@natefaubion I think we figured out that I was experiencing this problem because I was also using ide-purescript in Atom.

You mentioned that it was hard for tools to work together because psc doesn't persist errors.

Would that be the preferred solution?

**Comment by natefaubion** [comment]
@paulyoung That's why you were losing warnings. `psc-ide` was compiling your project in the background, so when you went to run a build in your console, you had an empty set. The projects could probably work together if we intercepted a `--json-errors` argument. Then you could just configure your psc-ide exec to psa and it would work fine.

**Comment by paulyoung** [comment]
Just wanted to confirm that this appears to be working as expected for me. Thanks!
