### ISSUE TITLE
Retry with "psc.cmd" for Windows

### ISSUE THREAD

**Issue by hdgarrood** [natefaubion/purescript-psa#13]
If someone is running Windows, and has installed the purescript compiler via `npm install -g purescript`, then the `psc` in their path will be `psc.cmd`, not `psc.exe`. Unfortunately, for reasons I don't quite understand (probably historical), `Node.ChildProcess.spawn` does not find executables unless they end with `.exe`.

Pulp resolves this by retrying failed commands with `.cmd` on the end if the error code was `ENOENT` (see: https://github.com/bodil/pulp/blob/master/src/Pulp/Exec.purs#L133-L146) but IIRC there's also a node wrapper around the `child_process` api that handles this for you too somewhere.

**Comment by natefaubion** [comment]
Fixed in 0.3.5

**Comment by hdgarrood** [comment]
:D thanks!
