### ISSUE TITLE
Allow shell expansion of paths in --psc

### ISSUE THREAD

**Issue by adinapoli** [natefaubion/purescript-psa#16]
Hey @natefaubion !

Do you think it will make sense for psa to be able to expand shell env variables when a path to --psc is passed? It would allow doing something like this, for example:

```
psa --psc=$(HOME)/path/to/custom/psc
```

Dunno if it's just the late hour, or me doing something stupid, but I wasn't able to get this to work as I was expecting :wink: 

Thank you!

Alfredo

**Comment by natefaubion** [comment]
Note quite sure what you mean? Shell expansion should work before the command is even run:

```
$ psa --psc=$HOME/foo/bar/psc
```
```
Error: `/Users/nathan/foo/bar/psc` executable not found.
```

**Comment by adinapoli** [comment]
I warned you it might have been some late night hacking hallucination :wink: 

I had `psa` being called as a part of a more complex executable, and I wanted to rule out one variable of the equation. Indeed the escaping works as expected as it happens at the shell level. I think I was erroneously expanding with the `$(VAR)` syntax, which made things even more confusing.

Sorry for the noise!

A.
