### ISSUE TITLE
--censor-codes with --json-errors

### ISSUE THREAD

**Issue by damncabbage** [natefaubion/purescript-psa#18]
These lines in Main switch on jsonErrors and either print out the errors directly, or put it through the filtering process: https://github.com/natefaubion/purescript-psa/blob/b40750bd5281b84d81d4f8ee0961a3e8929e17cb/bin/src/Main.purs#L197-L199

The comment says that it dumps out the JSON for further tooling. Do you intend for psa to not do any filtering (leaving it to an IDE, for example), even used in the context of an explicit `pulp build -I test --json-errors --censor-codes=HidingImport` (for example), or is this a bug / oversight?

**Edit**: I understand if you want to push it further down the line. My own preference would be to have psa use the same filtering for JSON as it does with straight output, if told to do so. If you don't want that, then I think I'd almost prefer it being an error if you provide both `--json-errors` and filter flags; the current situation is a "is this a bug?" grey-zone.

**Comment by natefaubion** [comment]
It should filter, I just haven't gotten around to it because it requires more JSON parsing rules. Though I suppose everything we don't use could just be parsed as Foreign. PRs welcome, but I'll also try to get around to it this week, as it should be fixed.

**Comment by natefaubion** [comment]
This should be fixed in 0.3.7.

**Comment by damncabbage** [comment]
Nice! Thanks a lot. :-)
