### ISSUE TITLE
ENOENT error when using `psa` to compile

### ISSUE THREAD

**Issue by hdgarrood** [natefaubion/purescript-psa#37]
See https://github.com/purescript-contrib/pulp/issues/354; this seems to me to be a psa issue rather than a pulp issue. Have you seen this before / can you help? I have seen this locally with pulp 12.3.0 and psa 0.7.2 but I haven't been able to reproduce it consistently.

**Comment by dwhitney** [comment]
Came here to report this too. I am running npm v6.4.0 and node v8.11.1. I get this with both purescript-psa v0.7.2 and v0.6.0.

**Comment by natefaubion** [comment]
While psa should handle this gracefully, this is caused by the compiler reporting a module and position information, but setting the file to an empty string.
