### ISSUE TITLE
Display progress somehow?

### ISSUE THREAD

**Issue by hdgarrood** [natefaubion/purescript-psa#4]
Not sure what the best way of doing this would be. Perhaps we can get `psc` to output progress messages on stderr?

**Comment by natefaubion** [comment]
There's the "Compiling SomeModule" output, which is on stdout I think. I'm dropping it atm.

**Comment by hdgarrood** [comment]
Right, yeah. But I think we can do better than that. Eg, what if it printed `Compiling: {Module} ({n}/{total})\r`? I guess that ought to be changed in the compiler, though?

**Comment by natefaubion** [comment]
Yeah it would be nice have progress like that, but `psc` would have to tell us how many module there are at the start. I don't know if it even knows that since it does a lot in parallel.

**Comment by natefaubion** [comment]
It should at least pipe stdout now https://github.com/natefaubion/purescript-psa/blob/0b92f57978e0da6d88dceb2e5f7fe30e5fd6d699/bin/src/Main.purs#L160

**Comment by hdgarrood** [comment]
Cool :) might be better to connect the child's stdout directly to the process' stdout, though? http://pursuit.purescript.org/packages/purescript-node-child-process/0.5.0/docs/Node.ChildProcess#t:StdIOBehaviour

**Comment by hdgarrood** [comment]
Ok reading the docs again this is not very clear at all... anyway, I think you might want this instead:

```purescript
Child.spawn (...) Child.defaultSpawnOptions { stdio = stdio }
where
stdio = [ Child.Pipe, unsafeIndex Child.inherit 1, Child.Pipe ]
```

**Comment by natefaubion** [comment]
https://github.com/natefaubion/purescript-psa/commit/419e055f6d012461bed530ee92157c24c2a8f2e9
