### ISSUE TITLE
Update for 0.14

### ISSUE THREAD

**Issue by hdgarrood** [natefaubion/purescript-psa#43]
0.14 will emit --json-errors to stdout rather than stderr, so psa needs to be updated to read from the appropriate stream. I am happy to volunteer to take this on. Presumably we'll want to query the compiler version and read from either stdout or stderr as appropriate, so that we can release a version of psa which works with both 0.13.x and 0.14.x? Are you happy to add a dependency on `purescript-versions` to achieve this?

**Comment by natefaubion** [comment]
> Are you happy to add a dependency on purescript-versions to achieve this?

That's fine.

**Comment by natefaubion** [comment]
This was published as part of 0.8.0
