### ISSUE TITLE
Windows: need to manually pass globs to the compiler

### ISSUE THREAD

**Issue by garyb** [natefaubion/purescript-psa#8]
I got the impression `psa` is supposed to know about the `lib` (or `bower_components`) and `src` paths out of the box and compile with those automatically, however that seems not to happen on Windows and no files are detected unless everything is passed through manually.

Perhaps need to use a platform specific delimiter?

**Comment by natefaubion** [comment]
It's not an alternative to pulp, so it just passes options straight through to psc. You provide globs just like you would to psc. Psa just checks for bower_components (by default) in the error JSON to determine if it's a lib file or not.

Or in other words, psa doesn't itself provide any secret sauce besides just making error/warning reporting nicer.

**Comment by garyb** [comment]
Ah okay, so the `lib` option is for filtering then, got it!

**Comment by natefaubion** [comment]
Oh, the `--lib-dir` flag. I can see how that is confusing. Perhaps it needs a better name.
